
CREATE TABLE STUDENTS(
ID INT PRIMARY KEY,
NAME TEXT NOT NULL,
AGE INT,
CITY,
GRADE REAL NOT NULL
);


INSERT INTO  STUDENTS (ID,NAME,AGE,CITY,GRADE )
VALUES (1,'Noa',15,'Tel Aviv',92.5),
(2,'Liam',16,'Haifa',88.0),
(3, 'Maya',15,'Netanya',95.0),
(4,'Omer',17,'Jerusalem',81.5 );

SELECT * FROM STUDENTS;

SELECT NAME,GRADE
FROM STUDENTS;

SELECT NAME,GRADE 
FROM STUDENTS
WHERE GRADE> 90;

SELECT NAME
FROM STUDENTS
WHERE NAME LIKE 'M%';

SELECT AVG(GRADE) FROM STUDENTS;
SELECT MAX(GRADE) FROM STUDENTS;
SELECT MIN(GRADE) FROM STUDENTS;

SELECT *
FROM STUDENTS
WHERE  GRADE> (
  SELECT AVG(GRADE) FROM STUDENTS
);

UPDATE STUDENTS
SET GRADE=90
WHERE NAME = 'Liam';

DELETE FROM STUDENTS
WHERE CITY LIKE 'N%';

DELETE FROM STUDENTS
WHERE CITY LIKE 'N%';

DROP TABLE STUDENTS;
